{
    'name': 'Miembros - Don Tello',
    'version': '1.0',
    'summary': 'Gestión de socios y actividades del club de golf Don Tello',
    'author': 'Adrian Muriel y Pablo Galván',
    'depends': ['base', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/golf_menus.xml',  
        'views/golf_member_views.xml',
        'views/golf_membership_type_views.xml',
        'views/golf_event_checkin_wizard_views.xml',
        'views/golf_event_checkout_wizard_views.xml',
        'views/golf_event_views.xml',
        'views/golf_booking_views.xml',
        # 'views/golf_reservation_views.xml',
        'views/golf_staff_views.xml',
        # 'views/golf_lesson_views.xml',
        # 'views/golf_fitting_views.xml',
        'views/golf_fee_rates_views.xml',
        # 'views/golf_sport_views.xml',
        'data/sports_data.xml',
        'data/membership_type_data.xml',
        'data/fee_rate_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
